#!/bin/bash

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

if [ ! -f saxo ]
then echo 'Error: saxo script not found'
    exit 1
fi

./saxo create /tmp/saxo-test
sed "s/localhost/$(hostname)/g" test/config > /tmp/saxo-test/config
./saxo -f start /tmp/saxo-test

rm -rf /tmp/saxo-test
