#!/bin/bash

# Copyright 2012-3, Sean B. Palmer
# Source: http://inamidst.com/saxo/

if [ ! -f saxo ]
then echo 'Error: saxo script not found'
    exit 1
fi

./saxo create /tmp/saxo-test
cp test/config /tmp/saxo-test/config
./saxo -f start /tmp/saxo-test

rm -rf /tmp/saxo-test
