#!/bin/bash

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

if [ ! -x test/shell-commands ]
then echo Error: test/shell-commands not found
     exit 1
fi

OUTPUT=/tmp/$$.0edf386273
test/shell-commands &> $OUTPUT
diff test/shell-commands-output.txt $OUTPUT
rm $OUTPUT
