#!/usr/bin/env python3

# Copyright 2013, Sean B. Palmer
# Source: http://inamidst.com/saxo/

import sys

def main():
    # Save PEP 3122!
    if "." in __name__:
        from . import scheduler
    else:
        import scheduler

    base = sys.argv[1]
    scheduler.start(base)

if __name__ == "__main__":
    main()
