#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.pipe
def authorised(arg):
    if saxo.env("authorised"):
        return "You are an authorised user"
    return "You are not an authorised user"
