#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.pipe
def bch(arg):
    if arg:
        return "This command takes no argument"
    url = "https://coinmarketcap.com/currencies/bitcoin-cash/"
    page = saxo.request(url)
    res = page["text"].split('data-usd="', 1).pop()
    return res.split('">', 1).pop(0).lstrip("$") + " USD (Coinmarketcap)"
