#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import re
import urllib.parse

import saxo

@saxo.command()
def bing(arg):
    if not arg:
        return "Search for a query on Bing (Web)"
    regex_bing_result = re.compile(r"<h2><a href=\"([^\"]+)\"")
    page = saxo.request("http://www.bing.com/search",
        query={"mkt": "en-GB", "q": arg}, modern=True)

    for url in regex_bing_result.findall(page["text"]):
        if "r.msn.com/" in url:
            continue
        if url.startswith("/"):
            continue
        return url
    return "No result found"
