#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.pipe
def _bytes(arg):
    if not arg:
        return "Zero-length input"

    if arg.startswith(":dec "):
        arg = arg[5:]
        format = "%d"
    else:
        format = "%02X"

    parts = [format % b for b in arg.encode("utf-8")]
    return " ".join(parts) + " (as utf-8)"
