#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import urllib.parse
import saxo

@saxo.command()
def c(arg):
    return "http://www.wolframalpha.com/input/?i=" + urllib.parse.quote(arg)
