#!/usr/bin/env python3

# Created by Mustafa Al-Bassam

import json

import saxo

@saxo.pipe
def cc(arg):
    page = saxo.request("http://coinmarketcap.northpole.ro/api/" + arg.lower()
                        + ".json")

    try:
        data = json.loads(page["text"])
    except ValueError:
        return "No data available on that alleged cryptocurrency"

    result = data["name"] + ". "
    result += "Price: $" + data["price"] + ". "
    result += "Market cap: $" + data["marketCap"] + ". "
    result += "Current supply: " + data["totalSupply"] + ". "
    result += "Volume (24h): $" + data["volume24"] + ". "
    result += "Change (24h): " + data["change24"].replace(" ", "") + "."

    return result
