#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import urllib.parse
import saxo

@saxo.pipe
def dety(arg):
    if not arg:
        return "Get etymology of a German word"
    arg = urllib.parse.quote(arg)
    page = saxo.request("http://dpk.io/s2/dety/{}".format(arg))
    return page["text"]
