#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import re
import urllib.parse

import saxo

@saxo.command()
def dim(arg):
    arg = urllib.parse.quote(arg)
    url = "https://duckduckgo.com/i.js?l=wt-wt&o=json&q=" + arg
    page = saxo.request(url)
    for result in re.findall(r'"([^"]*?\.[pj][np]g)"', page["text"]):
        if result.startswith("http"):
            return result
    return "Oh no, Duck turned into Bing!"
