#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import os
import saxo

url = "http://websitedev.de/temp-bin/distance.php"

@saxo.pipe
def distance(arg):
    nick = os.environ.get("SAXO_NICK", "result")
    page = saxo.request(url, query={"nick": nick, "q": arg})
    return page["text"]
