#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import re
import saxo

@saxo.pipe
def duck(arg):
    regex_duck_result = re.compile(r'nofollow" class="[^"]+" href="(.*?)">')

    page = saxo.request("http://duckduckgo.com/html/",
        query={"q": arg.replace("!", ""), "kl": "uk-en"})

    for link in regex_duck_result.findall(page["text"]):
        if "r.duckduckgo.com" in link:
            continue
        return link
    raise Error("No result found for %r" % arg)
