#!/usr/bin/env python3

# Copyright 2012-3, Sean B. Palmer
# Source: http://inamidst.com/saxo/

import json
import saxo

@saxo.pipe
def g(arg):
    if not arg:
        return "Search for a phrase on Google"

    page = saxo.request("https://www.google.com/search",
        query={"q": arg, "btnI": ""},
        headers={"Referer": "https://www.google.com/"})

    if "Location" in page["info"]:
        return page["info"]["Location"]
    return "No result for %s" % arg
