#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.command(authorised=True, private=True)
def g_default(arg):
    base = saxo.env("base")
    if not base:
        return "Error: Missing SAXO_BASE"

    if arg:
        saxo.data("default", arg)
        return "Set g-default.default to %s" % arg
    else:
        return saxo.data("default") or "Sorry, no key has been set"
