#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import json
import saxo

@saxo.pipe
def img(arg):
    page = saxo.request(
        "http://ajax.googleapis.com/ajax/services/search/images",
        query={"q": arg, "v": "1.0", "safe": "off"}, modern=True)
    data = json.loads(page["text"])
    try: result = data["responseData"]["results"][0]["unescapedUrl"]
    except (KeyError, IndexError, TypeError):
        return "No image search result found"
    return result
