#!/usr/bin/env python3

import json
import saxo

@saxo.pipe
def github_test(arg):
    page = saxo.request("https://api.github.com/repos/" + arg)
    data = json.loads(page["text"])
    return data["description"]
