#!/usr/bin/env python3

# Copyright 2014, Sean B. Palmer
# Source: http://inamidst.com/saxo/

import saxo

@saxo.pipe
def head(arg):
    if not arg:
        return "Please supply a URL"

    page = saxo.request(arg)
    values = [str(page["status"])]

    if "mime" in page:
        values.append(page["mime"])

    if "encoding" in page:
        if "encoding-source" in page:
            values.append(page["encoding"] + " (%s)" % page["encoding-source"])
        else:
            values.append(page["encoding"])

    if "last-modified" in page["headers"]:
        values.append("modified " + page["headers"]["last-modified"])

    if "content-length" in page["headers"]:
        values.append(page["headers"]["content-length"] + " bytes")

    return ", ".join(values)
