#!/usr/bin/env python3

# Copyright 2012-3, Sean B. Palmer
# Source: http://inamidst.com/saxo/

import json
import saxo

@saxo.pipe
def img(arg):
    page = saxo.request(
        "http://ajax.googleapis.com/ajax/services/search/images",
        query={"q": arg, "v": "1.0", "safe": "off"}
    )
    data = json.loads(page["text"])
    try: result = data["responseData"]["results"][0]["unescapedUrl"]
    except (KeyError, IndexError, TypeError):
        return "No image search result found"
    return result
