#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import re
import saxo

@saxo.command()
def isup(arg):
    page = saxo.request("http://isup.me/" + arg)
    pattern = r'(?ims)<div id="container">(.*?)<p>'
    for result in re.findall(pattern, page["text"]):
        text = re.sub(r"<[^>]+>", "", result)
        return '"' + text.strip().replace("  ", " ") + '"'
    return "Couldn't get data from isup.me. Maybe it's down?"
