#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import os, site
site.addsitedir(os.path.dirname(__file__))
import saxo

@saxo._command(authorised=True, private=True)
def join(arg):
    if arg.startswith("#"):
        saxo.client("join", arg)
        return "Joining %s" % arg
    else:
        return "Expected a channel name"
