#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.command(authorised=True, private=True)
def join(arg):
    if arg.startswith("#"):
        saxo.client("join", arg)
        return "Joining %s" % arg
    else:
        return "Expected a channel name"
