#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.pipe
def _len(arg):
    charlen = len(arg)
    bytelen = len(arg.encode("utf-8"))
    return "%s chars, %s bytes (utf-8)" % (charlen, bytelen)
