#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.pipe
def location(arg):
    arg = arg if arg else saxo.env("url")
    if not arg:
        return "Please supply a URL"
    page = saxo.request(arg)
    return page["url"]
