#!/usr/bin/env python3

import re
import urllib.parse
import saxo

@saxo.command()
def lpd(arg):
    arg = urllib.parse.quote(arg)
    page = saxo.request("http://services.nonceword.org/p/lpd/" + arg)
    text = page["text"]
    return text
