#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.pipe
def ng(arg):
    nick = saxo.env("nick") or "-"
    page = saxo.request("http://www.websitedev.de/temp-bin/ng.pl",
                        query={"nick": nick, "q": arg})
    return page["text"]
