#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.pipe
def nokiageo(arg):
    page = saxo.request("http://crschmidt.net/mapping/location",
                        query={"q": arg})
    return page["text"] or "No results found"
