#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import random
import saxo

@saxo.pipe
def pick(arg):
    if ", " in arg:
        choices = arg.split(", ")
    else:
        choices = arg.split(" ")
    return random.choice(choices)
