#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.command()
def pipe(arg):
    if (not arg) or (" " not in arg):
        return "For example, .pipe news|title Tony Blair"
    pipeline, arg = arg.split(" ", 1)
    cmds = pipeline.split("|")
    for cmd in cmds:
        if ("." in cmd) or ("\x00" in cmd) or ("/" in cmd):
            return "Not a valid command: %s" % cmd
    for cmd in cmds:
        arg = saxo.call(cmd, arg)
    return arg
