#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.command(authorised=True, private=True)
def prefix(arg):
    if arg:
        saxo.client("prefix", arg)
        return "Setting prefix to %r" % arg
    else:
        return "Expected a prefix"
