#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import os
import saxo

@saxo.command(authorised=True, private=True)
def public_channel(arg):
    path = os.path.join(saxo.env("base"), "database.sqlite3")
    with saxo.database(path) as db:
        if "saxo_private" in db:
            deleted = False
            query = "SELECT * FROM saxo_private WHERE channel = ?"
            for row in db.query(query, arg):
                del db["saxo_private"][row]
                deleted = True
            if deleted:
                return "Set %s as public" % arg
            else:
                return "Already set as public"
