#!/usr/bin/env python3

# Copyright 2012-3, Sean B. Palmer
# Source: http://inamidst.com/saxo/

import urllib.parse
import saxo

@saxo.pipe
def py(arg):
    page = saxo.request("http://tumbolia.appspot.com/py/" + urllib.parse.quote(arg))
    return page["text"]
