#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import urllib.parse
import saxo

@saxo.pipe
def r2r(arg):
    arg = urllib.parse.quote(arg)
    page = saxo.request("http://services.nonceword.org/p/rome2rio/" + arg)
    return page["text"]
