#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.command(authorised=True, private=True)
def reload(arg):
    saxo.client("reload", saxo.env("sender"))
