#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import os
import unicodedata

import saxo

def delete_table(db):
    del db["saxo_unicode"]

@saxo.command(authorised=True, private=True)
def remove_unicode_data(irc):
    path = os.path.join(saxo.env("base"), "database.sqlite3")
    with saxo.database(path) as db:
        if "saxo_unicode" not in db:
            return "No saxo_unicode table in database.sqlite3"
        delete_table(db)
    return "Removed saxo_unicode from database.sqlite3"
