#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import urllib.parse
import saxo

@saxo.pipe
def roll(arg):
    if not arg:
        return "Let me roll it"
    arg = urllib.parse.quote(arg)
    page = saxo.request("http://services.nonceword.org/p/roll/{}".format(arg))
    return page["text"]
