#!/usr/bin/env python3

import time

base = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
y, m, d, H, M, S = time.gmtime()[:6]
print(base[y % 50] + base[m] + base[d] + base[H] + base[M] + base[S])
