#!/usr/bin/env python3

import saxo
import time

@saxo.pipe
def sleep(text):
    duration = int(text)
    before = time.time()
    time.sleep(duration)

    return "Slept for %s seconds" % (time.time() - before)
