#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.pipe
def suggest(arg):
    page = saxo.request("http://websitedev.de/temp-bin/suggest.pl",
        query={"q": arg})
    return page["text"]
