#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import os.path
import sys

commands = os.path.dirname(__file__)
sys.path.append(os.path.join(commands, ".saxo-path"))

import saxo

@saxo.pipe
def suggest(arg):
    page = saxo.request("http://websitedev.de/temp-bin/suggest.pl",
        query={"q": arg})
    return page["text"]
