#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import urllib.parse
import saxo

@saxo.pipe
def thesaurus(arg):
    arg = urllib.parse.quote(arg)
    page = saxo.request("http://services.nonceword.org/r/thesaurus/" + arg)
    return page["text"]
