#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import time

import saxo

@saxo.pipe
def tw(arg):
    if not arg:
        arg = saxo.env("url")
        if arg is None:
            return "Show a tweet from a link, username, or tweet id"

    response = saxo.request("http://services.nonceword.org/r/tw/" + arg)
    return response["text"]
