#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import os.path
import sys
import urllib.parse

commands = os.path.dirname(__file__)
sys.path.append(os.path.join(commands, ".saxo-path"))

import saxo

@saxo.pipe
def twop(arg):
    page = saxo.request("http://services.w3.org/xslt?xslfile=http%3A%2F%2Fwww.websitedev.de%2Ftemp%2Fmobile-twitter-toptweet.xslt&xmlfile=http%3A%2F%2Fservices.w3.org%2Ftidy%2Ftidy%3FdocAddr%3Dhttps%253A%252F%252Fmobile.twitter.com%252Fsearch%253Fq%253D{}&content-type=text%2Fplain%3Bcharset%3Dutf-8&submit=transform".format(urllib.parse.quote(urllib.parse.quote(arg.replace(" ", "+")))))
    return page["text"]
