#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import os
import re

import saxo

def search_by_name(db, search):
    regex_metachar = re.compile("[%s]" % re.escape(r"$()*+.?[\]^{|}"))
    if regex_metachar.search(search):
        pattern = search
    else:
        pattern = ".*".join(r"\b" + word for word in search.split(" "))
    pattern = "(?i)" + pattern

    results = []
    query = "SELECT * FROM saxo_unicode WHERE name REGEXP ?"
    for row in db.query(query, pattern):
        codepoint = row[1]
        name = row[2]

        length = len(name) / 60
        length = length if (length <= .5) else .5

        position = codepoint / 0xFFFF
        position = position if (position <= 1) else 1

        weight = length + position
        # DerivedAge might make a good weight

        results.append((weight, row))

    if not results:
        return "No characters found"

    for weight, row in sorted(results):
        # hexcode, name, display
        return "U+%s %s (%s)" % (row[0], row[2], row[7])

@saxo.pipe
def unicode_by_name(arg):
    if not arg:
        return "Search for Unicode characters"

    base = saxo.env("base") or os.path.expanduser("~/.saxo")
    path = os.path.join(base, "database.sqlite3")
    with saxo.database(path) as db:
        if not "saxo_unicode" in db:
            return "The unicode database needs to be updated"

        return search_by_name(db, arg)
