#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import sys

def upper(text):
    return text.upper()

if __name__ == "__main__":
    for line in sys.stdin:
        line = line[:-1]
        print(upper(line))
        # break
