#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.pipe
def url(arg):
    url = saxo.env("url")
    if url is None:
        return "Sorry, no URL was found"
    return url
