#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import saxo

@saxo.command(authorised=True, private=True)
def visit(arg):
    if arg.startswith("#"):
        saxo.client("send", "JOIN", arg)
        return "Visiting %s" % arg
    else:
        return "Expected a channel name"
