#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import urllib.parse
import saxo

@saxo.command()
def wa(arg):
    arg = urllib.parse.quote(arg)
    page = saxo.request("http://ch0wn.org/oblique/wa?" + arg)
    return page["text"].strip()
